### ISSUE TITLE
'Unknown attribute' error when running rake db:seed

### ISSUE THREAD

**Issue by ross39** [gmit-sweng-20/sweng-project-ross39#1]
![Screenshot 2020-05-12 at 19 53 10](https://user-images.githubusercontent.com/20873258/81733723-6179ee80-948a-11ea-9bfe-4afc44014374.png)

Running into this issue when running the rake db:seed command. I've tried googling the problem but haven't found a solution yet. I've set up my seeds.rb file and have ran the command 'rake db:migrate' then when I go to run 'rake db:seed' this issue happens. I'm quite obviously doing something wrong. I would be grateful for any help

**Comment by john-french** [comment]
Hi @ross39. [Your migration](https://github.com/gmit-sweng-20/sweng-project-ross39/blob/d6eb1c37bde3d6e653c346d33042b4965b7fcecb/db/migrate/20200512160909_create_books.rb#L3) creates a table, but doesn't say anything about what that table should look like, i.e. column/field names, types etc. So rake isn't able to save the books you've defined in `seeds.rb` to this empty table. You need to set up the fields and data types in the migration.

**Comment by ross39** [comment]
Thanks John, that seems to be the problem. Definitely overlooked that. Thanks
